# Generated by Django 5.1.3 on 2024-12-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="key",
        ),
        migrations.CreateModel(
            name="CustomerSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_korean", models.BooleanField(default=True)),
                ("key", models.CharField(default="000000", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
