name: CI for Python Project

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout 코드
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Python 세팅
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 원하는 Python 버전

    # 3. Poetry 설치
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "::add-path::${HOME}/.local/bin"

    # 4. Dependencies 설치
    - name: Install dependencies
      run: |
        poetry install

    # 5. 스크립트 실행
    - name: Run tests
      run: |
        chmod +x scripts/test.sh
        ./scripts/test.sh
