name: CI for Python Project

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Add Poetry to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      working-directory: backend  # backend 디렉토리에서 설치
      run: poetry install

    - name: Run tests
      working-directory: backend/scripts  # scripts 디렉토리에서 실행
      run: |
        chmod +x test.sh
        ./test.sh
